version: '3.8'

services:
  # Backend REST API & Cron Jobs (Berjalan di STB 2)
  backend:
    build: ./backend
    container_name: roblox-backend
    restart: always
    env_file:
      - ./backend/.env.server1
    ports:
      - "7000:7000"
    volumes:
      - ./backend/logs:/app/logs
      - ./backend/uploads:/app/uploads
    networks:
      - roblox-network

  # Frontend Dashboard App (Berjalan di STB 2)
  frontend:
    build: ./frontend
    container_name: roblox-frontend
    restart: always
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=https://roblox-api.backendify.my.id # Domain backend publik Anda
    depends_on:
      - backend
    networks:
      - roblox-network

networks:
  roblox-network:
    driver: bridge
